Repository netdevops/hier_config, pull requests merged in 2018-06, with the labels that each got.

#24 [WIP] Documentation and Tests Updates
  hier_config/__init__.py
  hier_config/hc_child.py
  tests/test_hier_config.py
Labels: bug, documentation

#27 implement host object
  README.md
  hier_config/__init__.py
  hier_config/hc_child.py
  hier_config/host.py
  tests/test_hier_config.py
  tests/test_pep8.py
Labels: enhancement

#32 fixes issue31
  README.md
Labels: bug

#33 Extend host obj
  hier_config/__init__.py
  hier_config/host.py
  setup.py
  tests/test_host.py
  tests/tests.py
Labels: enhancement

#35 fix docstrings
  hier_config/host.py
Labels: documentation

#57 bug fixes identified by codefactor
  .travis.yml
  hier_config/__init__.py
  hier_config/hc_child.py
  hier_config/host.py
  setup.py
  tests/test_hier_config.py
  tests/test_host.py
Labels: bug

#59 Bug Fix: Python2 does not accurately compare running and compiled configs
  hier_config/__init__.py
  hier_config/hc_child.py
  tests/test_hier_config.py
Labels: bug

#60 Create a common base class for HConfig and HConfigChild
  hier_config/__init__.py
  hier_config/base.py
  hier_config/hc_child.py
Labels: enhancement

#62 mv has_children to base
  hier_config/base.py
  hier_config/hc_child.py
  tests/tests.py
Labels: bug
